### ISSUE TITLE
Incompatible with BetterSave (probably others too)

### ISSUE THREAD

**Issue by Bigmancozmo** [hiimjustin000/LevelSize#1]
In the levels menu, it can be seen that this overlaps with other buttons:
![image](https://github.com/hiimjustin000/LevelSize/assets/67850768/cdf6e0c4-c81a-4fba-8148-9aed308606aa)
I have already identified the cause, and it is because the "Sort by Level Size" button is not in "my-levels-menu"
![image](https://github.com/hiimjustin000/LevelSize/assets/67850768/e3b1af53-cb61-4c1b-9a2c-c5473c91b14a)

**Comment by hiimjasmine00** [comment]
I thought I added it to that menu, will get on it ASAP

**Comment by hiimjasmine00** [comment]
Will be fixed in v1.1.0 when accepted to the mod index
