### ISSUE TITLE
These buttons are over each other

### ISSUE THREAD

**Issue by 47837i** [hiimjustin000/LevelSize#2]
![330772090-1beddbd5-d82b-4758-bbf6-41192991cb03](https://github.com/hiimjustin000/LevelSize/assets/156704701/0733e133-1edc-4086-8ebe-e8d35287a0ac)

Fix that maybe

**Comment by hiimjasmine00** [comment]
Fixed in [v1.1.0](https://github.com/hiimjustin000/LevelSize/releases/download/v1.1.0/hiimjustin000.level_size.geode)
